// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewMeetup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UpdateMeetup struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}
